# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-59c3f8da-2cd7-4b6c-903c-af7a2f43dbe0";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-59c3f8da-2cd7-4b6c-903c-af7a2f43dbe0".device =
    "/dev/disk/by-uuid/59c3f8da-2cd7-4b6c-903c-af7a2f43dbe0";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-59c3f8da-2cd7-4b6c-903c-af7a2f43dbe0";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-59c3f8da-2cd7-4b6c-903c-af7a2f43dbe0";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B63B-F51A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-dbcf6bf5-db50-4ba6-81c0-af1cfe4cb8ce"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
